# SELECT 
#     P.PRICE_GROUP,
#     COUNT(*) AS PRODUCTS
# FROM (SELECT FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP FROM PRODUCT) P
# GROUP BY P.PRICE_GROUP
# ORDER BY P.PRICE_GROUP

SELECT
    FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP
