SELECT 
    T.ITEM_ID,
    C.ITEM_NAME,
    C.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO C ON T.ITEM_ID = C.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC;
