SELECT 
    F.ID,
    N.FISH_NAME,
    F.LENGTH
FROM (
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN
    FROM FISH_INFO
) F
JOIN FISH_NAME_INFO N ON F.FISH_TYPE = N.FISH_TYPE
WHERE F.RN = 1
ORDER BY F.ID;
