WITH RECURSIVE CTE AS (
    SELECT 
        ID, 
        PARENT_ID, 
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT 
        C.ID, 
        C.PARENT_ID, 
        P.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA C
    JOIN CTE P ON C.PARENT_ID = P.ID
)

SELECT 
    COUNT(*) AS COUNT,
    GENERATION
FROM CTE P
WHERE NOT EXISTS (
    SELECT 1
    FROM CTE C 
    WHERE C.PARENT_ID = P.ID
)
GROUP BY GENERATION
ORDER BY GENERATION
